/// Transform a character to it's mathematical italic equivalent.
pub fn math_italic(c: char) -> Option<char> {
    match c {
        // Latin capital letters.
        'A' => Some('𝐴'),
        'B' => Some('𝐵'),
        'C' => Some('𝐶'),
        'D' => Some('𝐷'),
        'E' => Some('𝐸'),
        'F' => Some('𝐹'),
        'G' => Some('𝐺'),
        'H' => Some('𝐻'),
        'I' => Some('𝐼'),
        'J' => Some('𝐽'),
        'K' => Some('𝐾'),
        'L' => Some('𝐿'),
        'M' => Some('𝑀'),
        'N' => Some('𝑁'),
        'O' => Some('𝑂'),
        'P' => Some('𝑃'),
        'Q' => Some('𝑄'),
        'R' => Some('𝑅'),
        'S' => Some('𝑆'),
        'T' => Some('𝑇'),
        'U' => Some('𝑈'),
        'V' => Some('𝑉'),
        'W' => Some('𝑊'),
        'X' => Some('𝑋'),
        'Y' => Some('𝑌'),
        'Z' => Some('𝑍'),

        // Latin small letters.
        'a' => Some('𝑎'),
        'b' => Some('𝑏'),
        'c' => Some('𝑐'),
        'd' => Some('𝑑'),
        'e' => Some('𝑒'),
        'f' => Some('𝑓'),
        'g' => Some('𝑔'),
        'h' => Some('ℎ'),
        'i' => Some('𝑖'),
        'j' => Some('𝑗'),
        'k' => Some('𝑘'),
        'l' => Some('𝑙'),
        'm' => Some('𝑚'),
        'n' => Some('𝑛'),
        'o' => Some('𝑜'),
        'p' => Some('𝑝'),
        'q' => Some('𝑞'),
        'r' => Some('𝑟'),
        's' => Some('𝑠'),
        't' => Some('𝑡'),
        'u' => Some('𝑢'),
        'v' => Some('𝑣'),
        'w' => Some('𝑤'),
        'x' => Some('𝑥'),
        'y' => Some('𝑦'),
        'z' => Some('𝑧'),
        'ı' => Some('𝚤'),
        'ȷ' => Some('𝚥'),

        // Greek capital letters.
        'Α' => Some('𝛢'),
        'Β' => Some('𝛣'),
        'Γ' => Some('𝛤'),
        'Δ' => Some('𝛥'),
        'Ε' => Some('𝛦'),
        'Ζ' => Some('𝛧'),
        'Η' => Some('𝛨'),
        'Θ' => Some('𝛩'),
        'Ι' => Some('𝛪'),
        'Κ' => Some('𝛫'),
        'Λ' => Some('𝛬'),
        'Μ' => Some('𝛭'),
        'Ν' => Some('𝛮'),
        'Ξ' => Some('𝛯'),
        'Ο' => Some('𝛰'),
        'Π' => Some('𝛱'),
        'Ρ' => Some('𝛲'),
        'ϴ' => Some('𝛳'),
        'Σ' => Some('𝛴'),
        'Τ' => Some('𝛵'),
        'Υ' => Some('𝛶'),
        'Φ' => Some('𝛷'),
        'Χ' => Some('𝛸'),
        'Ψ' => Some('𝛹'),
        'Ω' => Some('𝛺'),
        '∇' => Some('𝛻'),

        // Greek small letters
        'α' => Some('𝛼'),
        'β' => Some('𝛽'),
        'γ' => Some('𝛾'),
        'δ' => Some('𝛿'),
        'ε' => Some('𝜀'),
        'ζ' => Some('𝜁'),
        'η' => Some('𝜂'),
        'θ' => Some('𝜃'),
        'ι' => Some('𝜄'),
        'κ' => Some('𝜅'),
        'λ' => Some('𝜆'),
        'μ' => Some('𝜇'),
        'ν' => Some('𝜈'),
        'ξ' => Some('𝜉'),
        'ο' => Some('𝜊'),
        'π' => Some('𝜋'),
        'ρ' => Some('𝜌'),
        'ς' => Some('𝜍'),
        'σ' => Some('𝜎'),
        'τ' => Some('𝜏'),
        'υ' => Some('𝜐'),
        'φ' => Some('𝜑'),
        'χ' => Some('𝜒'),
        'ψ' => Some('𝜓'),
        'ω' => Some('𝜔'),
        '∂' => Some('𝜕'),
        'ϵ' => Some('𝜖'),
        'ϑ' => Some('𝜗'),
        'ϰ' => Some('𝜘'),
        'ϕ' => Some('𝜙'),
        'ϱ' => Some('𝜚'),
        'ϖ' => Some('𝜛'),

        // No equivalence.
        _ => None,
    }
}
