/// Transform a character to it's mathematical sans-serif bold italic
/// equivalent.
pub fn math_sans_serif_bold_italic(c: char) -> Option<char> {
    match c {
        // Latin capital letters.
        'A' => Some('𝘼'),
        'B' => Some('𝘽'),
        'C' => Some('𝘾'),
        'D' => Some('𝘿'),
        'E' => Some('𝙀'),
        'F' => Some('𝙁'),
        'G' => Some('𝙂'),
        'H' => Some('𝙃'),
        'I' => Some('𝙄'),
        'J' => Some('𝙅'),
        'K' => Some('𝙆'),
        'L' => Some('𝙇'),
        'M' => Some('𝙈'),
        'N' => Some('𝙉'),
        'O' => Some('𝙊'),
        'P' => Some('𝙋'),
        'Q' => Some('𝙌'),
        'R' => Some('𝙍'),
        'S' => Some('𝙎'),
        'T' => Some('𝙏'),
        'U' => Some('𝙐'),
        'V' => Some('𝙑'),
        'W' => Some('𝙒'),
        'X' => Some('𝙓'),
        'Y' => Some('𝙔'),
        'Z' => Some('𝙕'),

        // Latin small letters.
        'a' => Some('𝙖'),
        'b' => Some('𝙗'),
        'c' => Some('𝙘'),
        'd' => Some('𝙙'),
        'e' => Some('𝙚'),
        'f' => Some('𝙛'),
        'g' => Some('𝙜'),
        'h' => Some('𝙝'),
        'i' => Some('𝙞'),
        'j' => Some('𝙟'),
        'k' => Some('𝙠'),
        'l' => Some('𝙡'),
        'm' => Some('𝙢'),
        'n' => Some('𝙣'),
        'o' => Some('𝙤'),
        'p' => Some('𝙥'),
        'q' => Some('𝙦'),
        'r' => Some('𝙧'),
        's' => Some('𝙨'),
        't' => Some('𝙩'),
        'u' => Some('𝙪'),
        'v' => Some('𝙫'),
        'w' => Some('𝙬'),
        'x' => Some('𝙭'),
        'y' => Some('𝙮'),
        'z' => Some('𝙯'),

        // Greek capital letters.
        'Α' => Some('𝞐'),
        'Β' => Some('𝞑'),
        'Γ' => Some('𝞒'),
        'Δ' => Some('𝞓'),
        'Ε' => Some('𝞔'),
        'Ζ' => Some('𝞕'),
        'Η' => Some('𝞖'),
        'Θ' => Some('𝞗'),
        'Ι' => Some('𝞘'),
        'Κ' => Some('𝞙'),
        'Λ' => Some('𝞚'),
        'Μ' => Some('𝞛'),
        'Ν' => Some('𝞜'),
        'Ξ' => Some('𝞝'),
        'Ο' => Some('𝞞'),
        'Π' => Some('𝞟'),
        'Ρ' => Some('𝞠'),
        'ϴ' => Some('𝞡'),
        'Σ' => Some('𝞢'),
        'Τ' => Some('𝞣'),
        'Υ' => Some('𝞤'),
        'Φ' => Some('𝞥'),
        'Χ' => Some('𝞦'),
        'Ψ' => Some('𝞧'),
        'Ω' => Some('𝞨'),
        '∇' => Some('𝞩'),

        // Greek small letters
        'α' => Some('𝞪'),
        'β' => Some('𝞫'),
        'γ' => Some('𝞬'),
        'δ' => Some('𝞭'),
        'ε' => Some('𝞮'),
        'ζ' => Some('𝞯'),
        'η' => Some('𝞰'),
        'θ' => Some('𝞱'),
        'ι' => Some('𝞲'),
        'κ' => Some('𝞳'),
        'λ' => Some('𝞴'),
        'μ' => Some('𝞵'),
        'ν' => Some('𝞶'),
        'ξ' => Some('𝞷'),
        'ο' => Some('𝞸'),
        'π' => Some('𝞹'),
        'ρ' => Some('𝞺'),
        'ς' => Some('𝞻'),
        'σ' => Some('𝞼'),
        'τ' => Some('𝞽'),
        'υ' => Some('𝞾'),
        'φ' => Some('𝞿'),
        'χ' => Some('𝟀'),
        'ψ' => Some('𝟁'),
        'ω' => Some('𝟂'),
        '∂' => Some('𝟃'),
        'ϵ' => Some('𝟄'),
        'ϑ' => Some('𝟅'),
        'ϰ' => Some('𝟆'),
        'ϕ' => Some('𝟇'),
        'ϱ' => Some('𝟈'),
        'ϖ' => Some('𝟉'),
        // No equivalence.
        _ => None,
    }
}
