/// Transform a character to it's mathematical sans-serif bold
/// equivalent.
pub fn math_sans_serif_bold(c: char) -> Option<char> {
    match c {
        // Digits
        '0' => Some('𝟬'),
        '1' => Some('𝟭'),
        '2' => Some('𝟮'),
        '3' => Some('𝟯'),
        '4' => Some('𝟰'),
        '5' => Some('𝟱'),
        '6' => Some('𝟲'),
        '7' => Some('𝟳'),
        '8' => Some('𝟴'),
        '9' => Some('𝟵'),

        // Latin capital letters.
        'A' => Some('𝗔'),
        'B' => Some('𝗕'),
        'C' => Some('𝗖'),
        'D' => Some('𝗗'),
        'E' => Some('𝗘'),
        'F' => Some('𝗙'),
        'G' => Some('𝗚'),
        'H' => Some('𝗛'),
        'I' => Some('𝗜'),
        'J' => Some('𝗝'),
        'K' => Some('𝗞'),
        'L' => Some('𝗟'),
        'M' => Some('𝗠'),
        'N' => Some('𝗡'),
        'O' => Some('𝗢'),
        'P' => Some('𝗣'),
        'Q' => Some('𝗤'),
        'R' => Some('𝗥'),
        'S' => Some('𝗦'),
        'T' => Some('𝗧'),
        'U' => Some('𝗨'),
        'V' => Some('𝗩'),
        'W' => Some('𝗪'),
        'X' => Some('𝗫'),
        'Y' => Some('𝗬'),
        'Z' => Some('𝗭'),

        // Latin small letters.
        'a' => Some('𝗮'),
        'b' => Some('𝗯'),
        'c' => Some('𝗰'),
        'd' => Some('𝗱'),
        'e' => Some('𝗲'),
        'f' => Some('𝗳'),
        'g' => Some('𝗴'),
        'h' => Some('𝗵'),
        'i' => Some('𝗶'),
        'j' => Some('𝗷'),
        'k' => Some('𝗸'),
        'l' => Some('𝗹'),
        'm' => Some('𝗺'),
        'n' => Some('𝗻'),
        'o' => Some('𝗼'),
        'p' => Some('𝗽'),
        'q' => Some('𝗾'),
        'r' => Some('𝗿'),
        's' => Some('𝘀'),
        't' => Some('𝘁'),
        'u' => Some('𝘂'),
        'v' => Some('𝘃'),
        'w' => Some('𝘄'),
        'x' => Some('𝘅'),
        'y' => Some('𝘆'),
        'z' => Some('𝘇'),

        // Greek capital letters.
        'Α' => Some('𝝖'),
        'Β' => Some('𝝗'),
        'Γ' => Some('𝝘'),
        'Δ' => Some('𝝙'),
        'Ε' => Some('𝝚'),
        'Ζ' => Some('𝝛'),
        'Η' => Some('𝝜'),
        'Θ' => Some('𝝝'),
        'Ι' => Some('𝝞'),
        'Κ' => Some('𝝟'),
        'Λ' => Some('𝝠'),
        'Μ' => Some('𝝡'),
        'Ν' => Some('𝝢'),
        'Ξ' => Some('𝝣'),
        'Ο' => Some('𝝤'),
        'Π' => Some('𝝥'),
        'Ρ' => Some('𝝦'),
        'ϴ' => Some('𝝧'),
        'Σ' => Some('𝝨'),
        'Τ' => Some('𝝩'),
        'Υ' => Some('𝝪'),
        'Φ' => Some('𝝫'),
        'Χ' => Some('𝝬'),
        'Ψ' => Some('𝝭'),
        'Ω' => Some('𝝮'),
        '∇' => Some('𝝯'),

        // Greek small letters
        'α' => Some('𝝰'),
        'β' => Some('𝝱'),
        'γ' => Some('𝝲'),
        'δ' => Some('𝝳'),
        'ε' => Some('𝝴'),
        'ζ' => Some('𝝵'),
        'η' => Some('𝝶'),
        'θ' => Some('𝝷'),
        'ι' => Some('𝝸'),
        'κ' => Some('𝝹'),
        'λ' => Some('𝝺'),
        'μ' => Some('𝝻'),
        'ν' => Some('𝝼'),
        'ξ' => Some('𝝽'),
        'ο' => Some('𝝾'),
        'π' => Some('𝝿'),
        'ρ' => Some('𝞀'),
        'ς' => Some('𝞁'),
        'σ' => Some('𝞂'),
        'τ' => Some('𝞃'),
        'υ' => Some('𝞄'),
        'φ' => Some('𝞅'),
        'χ' => Some('𝞆'),
        'ψ' => Some('𝞇'),
        'ω' => Some('𝞈'),
        '∂' => Some('𝞉'),
        'ϵ' => Some('𝞊'),
        'ϑ' => Some('𝞋'),
        'ϰ' => Some('𝞌'),
        'ϕ' => Some('𝞍'),
        'ϱ' => Some('𝞎'),
        'ϖ' => Some('𝞏'),

        // No equivalence.
        _ => None,
    }
}
